[2025-03-07T06:11:28.694+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:11:28.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:11:28.712+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:11:28.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:11:28.730+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:11:28.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:11:28.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:11:28.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.079 seconds
[2025-03-07T06:12:00.562+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:00.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:12:00.570+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:12:00.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:00.590+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:12:00.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:12:00.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:00.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.067 seconds
[2025-03-07T06:12:31.670+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:31.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:12:31.677+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:12:31.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:31.696+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:12:31.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:12:31.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:12:31.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.059 seconds
[2025-03-07T06:13:02.722+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:02.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:13:02.729+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:13:02.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:02.743+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:13:02.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:13:02.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:02.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.071 seconds
[2025-03-07T06:13:33.726+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:33.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:13:33.735+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:13:33.734+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:33.745+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:13:33.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:13:33.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:13:33.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.039 seconds
[2025-03-07T06:14:05.166+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:05.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:14:05.172+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:14:05.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:05.179+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:14:05.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:14:05.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:05.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.052 seconds
[2025-03-07T06:14:36.434+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:36.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:14:36.447+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:14:36.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:36.470+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:14:36.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:14:36.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:14:36.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.109 seconds
[2025-03-07T06:15:07.821+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:07.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:15:07.855+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:15:07.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:07.882+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:15:07.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:15:07.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:07.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.106 seconds
[2025-03-07T06:15:39.128+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:39.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:15:39.147+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:15:39.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:39.160+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:15:39.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:15:39.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:15:39.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.104 seconds
[2025-03-07T06:16:11.102+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:11.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:16:11.113+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:16:11.112+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:11.121+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:16:11.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:16:11.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:11.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.055 seconds
[2025-03-07T06:16:41.730+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:41.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:16:41.739+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:16:41.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:41.754+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:16:41.753+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:16:41.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:16:41.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.067 seconds
[2025-03-07T06:17:12.766+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:17:12.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:17:12.775+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:17:12.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:17:12.788+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:17:12.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:17:12.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:17:12.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.068 seconds
[2025-03-07T06:18:07.249+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:07.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:18:07.255+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:18:07.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:07.266+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:18:07.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:18:07.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:07.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.039 seconds
[2025-03-07T06:18:38.550+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:38.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:18:38.560+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:18:38.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:38.565+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:18:38.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:18:38.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:18:38.604+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.062 seconds
[2025-03-07T06:19:11.150+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:11.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:19:11.158+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:19:11.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:11.172+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:19:11.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:19:11.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:11.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.064 seconds
[2025-03-07T06:19:42.438+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:42.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:19:42.446+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:19:42.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:42.454+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:19:42.452+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:19:42.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:19:42.490+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.059 seconds
[2025-03-07T06:20:13.569+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:13.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:20:13.575+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:20:13.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:13.584+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:20:13.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:20:13.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:13.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.054 seconds
[2025-03-07T06:20:44.561+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:44.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:20:44.573+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:20:44.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:44.596+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:20:44.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:20:44.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:20:44.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.063 seconds
[2025-03-07T06:21:15.705+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:15.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:21:15.716+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:21:15.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:15.721+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:21:15.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:21:15.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:15.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.067 seconds
[2025-03-07T06:21:46.977+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:46.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:21:46.995+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:21:46.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:47.005+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:21:47.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:21:47.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:21:47.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.069 seconds
[2025-03-07T06:22:18.019+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:18.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:22:18.025+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:22:18.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:18.033+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:22:18.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:22:18.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:18.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.051 seconds
[2025-03-07T06:22:49.169+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:49.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:22:49.179+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:22:49.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:49.186+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:22:49.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:22:49.187+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:22:49.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.065 seconds
[2025-03-07T06:23:20.419+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:20.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:23:20.440+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:20.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:20.450+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:20.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:23:20.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:20.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.066 seconds
[2025-03-07T06:23:51.674+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:51.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:23:51.682+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:51.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:51.693+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:23:51.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:23:51.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:23:51.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.067 seconds
[2025-03-07T06:24:22.337+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:22.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:24:22.344+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:24:22.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:22.355+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:24:22.354+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:24:22.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:22.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.053 seconds
[2025-03-07T06:24:52.520+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:52.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:24:52.526+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:24:52.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:52.533+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:24:52.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:24:52.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:24:52.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.044 seconds
[2025-03-07T06:25:23.572+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:23.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:25:23.588+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:25:23.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:23.601+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:25:23.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:25:23.601+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:23.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.058 seconds
[2025-03-07T06:25:53.678+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:53.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:25:53.682+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:25:53.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:53.690+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:25:53.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:25:53.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:25:53.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.052 seconds
[2025-03-07T06:26:24.729+0000] {processor.py:186} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:24.730+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:26:24.745+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:26:24.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:24.760+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:26:24.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:26:24.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:24.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.070 seconds
[2025-03-07T06:26:55.293+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:55.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:26:55.297+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:26:55.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:55.303+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:26:55.302+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:26:55.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:26:55.322+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.049 seconds
[2025-03-07T06:27:25.466+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:25.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:27:25.471+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:27:25.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:25.477+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:27:25.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:27:25.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:25.501+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.059 seconds
[2025-03-07T06:27:55.644+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:55.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:27:55.652+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:27:55.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:55.664+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:27:55.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:27:55.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:27:55.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.059 seconds
[2025-03-07T06:28:43.379+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:28:43.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:28:43.384+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:28:43.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:28:43.395+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:28:43.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:28:43.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:28:43.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.047 seconds
[2025-03-07T06:29:14.682+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:14.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:29:14.694+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:29:14.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:14.705+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:29:14.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:29:14.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:14.726+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.056 seconds
[2025-03-07T06:29:45.737+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:45.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:29:45.746+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:29:45.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:45.751+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:29:45.750+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:29:45.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:29:45.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.061 seconds
[2025-03-07T06:30:16.777+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:16.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:30:16.787+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:30:16.787+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:16.794+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:30:16.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:30:16.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:16.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.064 seconds
[2025-03-07T06:30:47.850+0000] {processor.py:186} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:47.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T06:30:47.859+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:30:47.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:47.865+0000] {logging_mixin.py:190} INFO - [2025-03-07T06:30:47.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 4, in <module>
    from pyspark.sql import SparkSession
ModuleNotFoundError: No module named 'pyspark'
[2025-03-07T06:30:47.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T06:30:47.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.050 seconds
[2025-03-07T07:23:23.235+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T07:23:23.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_daily_transaction_summary.py for tasks to queue
[2025-03-07T07:23:23.243+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:23:23.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T07:23:23.716+0000] {logging_mixin.py:190} INFO - [2025-03-07T07:23:23.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_daily_transaction_summary.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_daily_transaction_summary.py", line 71, in <module>
    AIRFLOW_PATH = Variable.get("LOCAL_AIRFLOW_PATH")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable LOCAL_AIRFLOW_PATH does not exist'
[2025-03-07T07:23:23.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_daily_transaction_summary.py
[2025-03-07T07:23:23.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_daily_transaction_summary.py took 0.493 seconds
